### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by davidanthoff** [davidanthoff/DataValues.jl#1]
Couple of simple questions:
- What should the name of the package be?
- What should the name of the type be? Currently it is `NAable`.
- What should the name of the function checking for missing values be? Currently it is `isna`.
- What should the name of the missing value be? Currently it is `NA`.

I'd like to get feedback, but also make a decision fairly soonish so that I can register the package and then have Query.jl depend on it.

I'm not a huge fan of `NAable`, but I _really_ like that we can keep using `isna` and `NA` with that choice. Plus, I feel that folks using this in e.g. Query.jl will more often have to use the latter two identifiers than the actual type name.

If anyone has a better name, please speak up! Having short names for the equivalent for `isna` and `NA` is a huge plus for such suggestions.

**Comment by ti-s** [comment]
How about `DataValue` for the name of the type? If the principle idea is to add the value `NA` to the possible values of `T` while making the use of `NAable{T}` instead of `T` as transparent as possible, the non-`NA` values of the `NAable`s would be mostly equivalent to the values of the data. A `DataArray` could then be an array of `DataValue`s and a `DataFrame` a collection of `DataArray`s.

In https://github.com/JuliaLang/julia/issues/5009, the name was already used for such a type.

**Comment by davidanthoff** [comment]
@ti-s I like that a lot, definitly better than ``NAable``. So unless someone comes along with an even better idea, I'll go with ``DataValue``. Thanks!

**Comment by davidanthoff** [comment]
Thanks again @ti-s, I'm going with that name now!
