### ISSUE TITLE
Add dot lifting support

### ISSUE THREAD

**Issue by davidanthoff** [davidanthoff/DataValues.jl#8]
Essentially we want the same broadcasting/``.`` syntax that lifts ``Nullable``s in base to also work with ``DataValue``.

@TotalVerb Is that generally doable? I naivly assumed that I just have to copy all the ``Nullable`` specific code from broadcast.jl in base in here, and then replace ``Nullable`` with ``DataValue``. Are there any further gotchas?

One line that made me nervous is [this](https://github.com/JuliaLang/julia/blob/master/base/broadcast.jl#L12), because that is probably something we can't extend from a package? Is that something we need to worry about?

Sorry for these pretty basic questions :)

**Comment by TotalVerb** [comment]
You're right that it's not possible to extend `ScalarType`, but it's not a big deal. It just means that for now, all methods defined on `ScalarType` will also need to be specialized for `Type{DataValue}` (alongside all methods defined on `Type{Nullable}`.

Otherwise, copying the `Nullable`-specific code should work. Please update me on how it goes; it will be useful to know in what ways people are extending `broadcast` so that the generic infrastructure can be improved in time for 1.0.

**Comment by davidanthoff** [comment]
Thanks, I'll let you know how it goes!
